/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmongo.gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;

/**
 * スクロールするパネル
 * 
 * @author mitsu
 */
public class ScrollPane extends javax.swing.JPanel {
    private Thread scroll_thread = null;
    private String m_value = "";
    
    private int cnt = 0;
    
    /**
     * Creates new form ScrollPane
     */
    public ScrollPane() {
        initComponents();
        
        scroll_thread = new Thread(new Runnable(){
            public void run(){
                while(isVisible()){
                    try{
                        cnt++;
                        repaint();
                        Thread.sleep(100);
                    }catch(Exception err){
                        err.printStackTrace();
                    }
                }
            }
        });
        
        scroll_thread.start();        
        
    }

    public void setPaintValue(String value){
        m_value = value;
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        String[] strArrays = m_value.split("\n");
        Graphics2D g2 = (Graphics2D)g;
        g2.setTransform(AffineTransform.getTranslateInstance(0, -(cnt * 1)));
        for(int i = 0 ; i < strArrays.length ; i++){
            g2.drawString(strArrays[i],  20, g2.getFontMetrics().getHeight() * i);
        }
        
        if(cnt*1 > g2.getFontMetrics().getHeight() * strArrays.length){
            cnt = 0;
        }
        
        g2.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
