/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmongo.gui;

import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import jmongo.MainController;

/**
 *
 * @author mitsu
 */
public class SplashWindow extends javax.swing.JWindow {

    private long repaintCnt = 0;

    /**
     * Creates new form SplashWindow
     */
    public SplashWindow() {
        initComponents();
        getContentPane().add(new _SplashPane());
        setBackground(new Color(0, 0, 0, 0));
        
        pack();
    }

    class _SplashPane extends JPanel {
        private float alpha = 1f;
        private ImageIcon imgTitle = new javax.swing.ImageIcon(MainController.class.getResource("/jmongo/icon/jmongo_cafe1.png"));
        private ImageIcon imgDuke = new javax.swing.ImageIcon(MainController.class.getResource("/jmongo/icon/surf_duke1.png"));
        
        public _SplashPane(){
            this.setOpaque(false);
            this.setPreferredSize(new Dimension(imgTitle.getIconWidth(), imgTitle.getIconHeight()));
        }
        
        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            repaintCnt++;

            Graphics2D g2 = (Graphics2D) g.create();
            g2.drawString("> now loading...", 10, 10);


            alpha = 1f-repaintCnt/250f;
            if(alpha < 0.001f)alpha = 0;
            g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, alpha));
            g2.drawImage(imgDuke.getImage(), (int)(getWidth()-repaintCnt*5), -30, this);
            g2.drawImage(imgTitle.getImage(), 0, 0, this);
            
            
            repaint();
        }

    }
    
    /**
     * アニメーションが終了した場合True
     *
     * @return
     */
    public boolean isAnimationEnd() {
        return (repaintCnt < 250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-870)/2, (screenSize.height-612)/2, 870, 612);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
