/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmongo.gui;

import java.awt.Frame;
import javax.swing.ImageIcon;

/**
 * Special Thanks Dlg
 * 
 * @author mitsu
 */
public class ThanksDlg extends javax.swing.JDialog{
    String staff_value = "\n"
            + "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
            + "■JMongo\n"
            + "  https://github.com/moremagic/JMongo\n"
            + "\n"
            + "                       edit by moremagic\n"
            + "                              [itoumagic@gmail.com]\n"
            + "\n"
            + "\n"
            + "■Special Thanks\n"
            + "\n"
            + "  ->shinsuke. o\n"
            + "   ->takashi.m\n"
            + "    ->mitsuhiro.s\n"
            + "\n"
            + "\n"
            + "    and...\n"
            + "\n"
            + "\n"
            + "\n"
            + "   MongoDB\n"
            + "   http://www.mongodb.org/"
            + "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
            + "   ばんばん ばんばん！\n";
    
    
    
    /**
     * Creates new form VersionDlg
     */
    public ThanksDlg(Frame owner) {
        super(owner);
        initComponents();

        this.backImagePane1.setImage(new javax.swing.ImageIcon(getClass().getResource("/jmongo/icon/photo.jpg")).getImage());
        
        this.setIconImage(new ImageIcon(getClass().getResource("/jmongo/icon/famfamfam_silk_icons_v013/icons/rainbow.png")).getImage());
        this.scrollPane1.setPaintValue(staff_value);
        
        this.uRLLinkLabel1.setURLString("http://www.mongodb.org/");
        this.uRLLinkLabel2.setURLString("https://github.com/moremagic/JMongo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        backImagePane1 = new jmongo.gui.BackImagePane();
        jPanel5 = new javax.swing.JPanel();
        uRLLinkLabel1 = new jmongo.gui.URLLinkLabel();
        uRLLinkLabel2 = new jmongo.gui.URLLinkLabel();
        scrollPane1 = new jmongo.gui.ScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("thanks dlg");
        setModal(true);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel2.setLayout(new java.awt.BorderLayout());

        backImagePane1.setLayout(new java.awt.BorderLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        uRLLinkLabel1.setText("uRLLinkLabel1");
        jPanel5.add(uRLLinkLabel1);
        jPanel5.add(uRLLinkLabel2);

        backImagePane1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel2.add(backImagePane1, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout scrollPane1Layout = new javax.swing.GroupLayout(scrollPane1);
        scrollPane1.setLayout(scrollPane1Layout);
        scrollPane1Layout.setHorizontalGroup(
            scrollPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        scrollPane1Layout.setVerticalGroup(
            scrollPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jPanel2.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-703)/2, (screenSize.height-327)/2, 703, 327);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanksDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanksDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanksDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanksDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ThanksDlg(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jmongo.gui.BackImagePane backImagePane1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private jmongo.gui.ScrollPane scrollPane1;
    private jmongo.gui.URLLinkLabel uRLLinkLabel1;
    private jmongo.gui.URLLinkLabel uRLLinkLabel2;
    // End of variables declaration//GEN-END:variables
}
