/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmongo.gui;

import java.awt.Desktop;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mitsu
 */
public class URLLinkLabel extends javax.swing.JLabel {

    /**
     * Creates new form URLLinkLabel
     */
    public URLLinkLabel() {
        initComponents();
    }
    
    public void setURLString(String url){
        this.setText(url);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        setForeground(new java.awt.Color(51, 51, 255));
        setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setText("http://example.com");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        try {
            URL url = new URL(getText());
            
            //デフォルトのブラウザーを使ってリンク先を表示
            Desktop dp = Desktop.getDesktop();
            dp.browse(url.toURI());
        }catch(Exception ex){
            Logger.getLogger(URLLinkLabel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
